image: docker:latest

services:
  - docker:dind

stages: 
  - analyse
  - build
  - test
  - watchus

include:
  - template: Code-Quality.gitlab-ci.yml


code-quality:
  stage: analyse
  artifacts:
    paths: [code-quality.json]

build:
  stage: build
  before_script:
    - docker login -u "$DOCKER_HUB_MARS3319_USERNAME" -p "$DOCKER_HUB_MARS3319_PASSWORD"
  script:
    - docker build -f ConnectionDB/Dockerfile -t smaraoui2/connectiondb .
    - docker build -f DeployUS/Dockerfile -t smaraoui2/deployus .
    - docker build -f WorkUs/Dockerfile -t smaraoui2/workus .
    - docker build -f client/Dockerfile -t smaraoui2/client .
    - docker push smaraoui2/connectiondb
    - docker push smaraoui2/deployus
    - docker push smaraoui2/workus
    - docker push smaraoui2/client


test:
  stage: test
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
    - docker run mars3319_test


watchus :
  stage: watchus
  script:
    - curl http://68.183.192.81:5005
    - curl http://178.128.238.88:5005
