image: docker:latest

services:
  - docker:dind

stages: 
  - build-push

build-push:
  stage: build-push
  before_script:
    - docker login -u "$DOCKER_HUB_MARS3319_USERNAME" -p "$DOCKER_HUB_MARS3319_PASSWORD"
  script:
    - docker build -f client/Dockerfile -t smaraoui2/client .
    - docker push smaraoui2/client